services:
  db:
    image: mysql:8.0
    container_name: lilmarket-db
    restart: always
    environment:
      MYSQL_DATABASE: lilmarket_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  api:
    image: lilmarket-api:v0.5.0
    container_name: lilmarket-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Padronizando tudo para lilmarket_db e usuário root
      - DB_URL=jdbc:mysql://db:3306/lilmarket_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - DB_USER=root
      - DB_PASS=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/lilmarket_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - BASIC_AUTH_USER=test
      - BASIC_AUTH_PASS=test123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect