server.servlet.context-path=/api
spring.main.banner-mode=off
logging.level.root = INFO
#logging.level.org.springframework.security=DEBUG
logging.level.com.eduribeiro8.LilMarket=DEBUG
logging.file.name=application%d{yyyy-MM-dd}.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n