spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

#Config JWT
api.security.token.secret=${JWT_SECRET_KEY}
api.security.token.expiration=3600000
api.security.refresh-token.expiration=1296000000