spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.security.user.name=${BASIC_AUTH_USER}
spring.security.user.password=${BASIC_AUTH_PASS}